SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_TYPE IN ('SUV', '세단') AND
            CAR_ID NOT IN (SELECT CAR_ID
                           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                           WHERE (START_DATE <= '2022-11-30') AND (END_DATE >= '2022-11-01'))) C
     JOIN (SELECT CAR_TYPE, MIN(DISCOUNT_RATE) DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE IN ('세단', 'SUV') AND REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') >= 30
            GROUP BY CAR_TYPE) D
     USING(CAR_TYPE)
HAVING FEE >= 500000 AND FEE < 2000000 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID