SELECT ID, CASE NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) 
           WHEN 1 THEN 'LOW'
           WHEN 2 THEN 'MEDIUM'
           WHEN 3 THEN 'HIGH'
           WHEN 4 THEN 'CRITICAL' 
           END COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID