WITH RECURSIVE ED AS (
     SELECT ID, PARENT_ID, 1 GENERATION
     FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
     UNION ALL
     SELECT E.ID, E.PARENT_ID, ED.GENERATION + 1
     FROM ECOLI_DATA E JOIN ED
     ON ED.ID = E.PARENT_ID) 
     
SELECT COUNT(ID) COUNT, GENERATION
FROM ED
WHERE ID NOT IN (SELECT DISTINCT(PARENT_ID)
                 FROM ECOLI_DATA
                 WHERE PARENT_ID IS NOT NULL)
GROUP BY 2  
ORDER BY 2