SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
     JOIN PATIENT P USING (PT_NO)
WHERE APNT_YMD LIKE '2022-04-13%'
      AND A.MCDP_CD = 'CS'
      AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD