WITH RECURSIVE CTE AS (
     SELECT 0 HOUR
     UNION ALL
     SELECT HOUR + 1
     FROM CTE
     WHERE HOUR < 23 )

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A RIGHT JOIN CTE C 
ON HOUR(A.DATETIME) = C.HOUR
GROUP BY HOUR
ORDER BY HOUR