SELECT F.FLAVOR AS FLAVOR
FROM FIRST_HALF F JOIN ICECREAM_INFO I
ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER >= 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC

-- SELECT FLAVOR
-- FROM FIRST_HALF
-- WHERE FLAVOR IN (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based') AND 
-- TOTAL_ORDER > 3000 
-- ORDER BY TOTAL_ORDER DESC