SELECT DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM HR_DEPARTMENT JOIN (SELECT DEPT_ID, ROUND(AVG(SAL)) AVG_SAL 
                         FROM HR_EMPLOYEES 
                         GROUP BY DEPT_ID) E
USING (DEPT_ID)
ORDER BY AVG_SAL DESC